### ISSUE TITLE
Database/Group Setup Loss since Game Update 6.55

### ISSUE THREAD

**Issue by Zero0815** [Koenari/HimbeertoniRaidTool#135]
Hello,

I have a problem with the plugin and it seems that the database/group setup has been deleted/no longer works since the 6.55 patch. Thanks to the "Just Backup" plugin, I still have the data on my computer, but I can't import it. Can I import the data, or is it only possible to re-enter all the data? I like to use this plugin, especially when questions arise about the lot when clearing or re-clearing content.

If needed i may supply you with the files.

**Comment by Koenari** [comment]
Sorry to hear, that happened to you.
One question, did you "regularly" use the plugin in the last year? If you haven't used since  around April 2023 it might be due to [compatibility issues](https://github.com/Koenari/HimbeertoniRaidTool?tab=readme-ov-file#compatibility-matrix). Then pleasse contact me personally on Discord @Koenari 
Generally all data is located in %appdata%\XIVLauncher\pluginConfigs\HimbeertoniRaidTool (copy & paste to the windows explorer navigation bar) and the contents should look like 
![HimbeertoniRaidTool-Config](https://github.com/Koenari/HimbeertoniRaidTool/assets/7422843/c6e4db99-8047-4c89-9ff0-5662c43515f1)
Files ending in DB.json contain your data moduleConfigs\Lootmaster.json contains information on which groups to show in the ui.
If you want to restore, disable the plugin then delete (maybe backup manually first) all files in this directory and copy the files from just backup. The re enable the plugin and it will try to migrate the data.
Feel free to ask more questions (Note: Do not post any of the files here, this is public and files may contain personal information)

**Comment by Zero0815** [comment]
Sorry, had been busy. Seems like it helped. I had to assign the members again but it saved the rest. :) Thanks a lot. :)
