### ISSUE TITLE
Fix "Update Gear"/"Open Examine" functionality for 6.2

### ISSUE THREAD

**Issue by vpcn2019** [Koenari/HimbeertoniRaidTool#27]
The "Update Gear" button on "Solo" tab behaves inconsistently. For me it does nothing. As in, the "Examine" window doesn't open, gear does not get updated and no error message appears anywhere in the game or in the logs. Manually opening "Examine" window before clicking the button didn't do anything either.
For a friend of mine, it had partial success when they pressed the button with "Examine" window opened for their character and it did update equipped gear. Didn't do anything before that though.

**Comment by Koenari** [comment]
Some clarification on current status:
The possibility to open examine by a button press is broken since 6.2 and therefore disabled. (Will happen for every major patch)
The button is by now diabled and has a tooltip to reflect this (in 0.4.1.19)
The plugin still fetches data about gear when Examine window pops open. So you just have to examine yourself/whoever manually at the moment. 
I am working on Ui and usability improvements with a few testers. Which will include all this information in game.
Unfortunately the fix for the underlying issue has no eta as it is non trivial.

**Comment by vpcn2019** [comment]
I see, thanks for the explanation :)
So how does the Examine part work exactly? Do I just "Examine" myself or whoever while having the window open, without any additional button presses/commands? Something like this worked for my friend but doesn't seem to be working for me

**Comment by ItsANoBrainer** [comment]
How do we manually force the update with examine? Doesnt seem to be working for me. I've selected myself and pressed examine with the LM window open with nothing updating.

**Comment by Fivavoa** [comment]
It seemed to work for me just fine when I updated myself and two other people, but it suddenly stopped being able to update after the third person. I tried updating two more people and it didn't want to register anymore.

**Comment by Koenari** [comment]
Firstly can you confirm you all are on Version 0.4.2.22 or newer? Thus version containing the last fixes for the gear update functionality. I will look into it again tomorrow, but the last tests I did in a current version did work fine with numerous characters. Can maybe see any pattern with the characters not working, like same home world, Amy special characters in names? And I guess you checked but make sure character names and Homeworld are correct in the plug-in? And very important question,  does anyone play in a different language than English?

**Comment by Fivavoa** [comment]
For me, I'm on Version 0.4.2.24, as seen here:
![image](https://user-images.githubusercontent.com/29827600/188103237-44f27344-009c-412f-b35f-bb9ef18640eb.png)

The characters I tested on had no special characters, I triple checked spelling and homeworld (which was easy because not only did the plugin get the homeworld for me, but they're also on my homeworld), and my client is regular English version. It's on Steam if it makes a difference.

As for testing, I closed the whole game and logged back in, I had them change classes and examined their new class, to change to their actual class to possibly refresh the examine queue or something, and neither approach worked.

**Comment by Koenari** [comment]
Thanks to your feedback, there is yet another hotfix out (0.4.2.25). Seems like with 0.4.2.22 I reintroduced some part of the issue fixed in 0.4.2.20. 
To be honest this whole code (around gear update/examine) is quite messy and will always be prone to errors, especially after updates, though I hope it is stable enough now. But this is why #28 and #32 exist. I just cannot give definitive dates as to when I get to it, since this takes a significant portion of my free time. I hope you understand.

**Comment by ItsANoBrainer** [comment]
Self examine seems to be working after the latest patch, thank you! 

This tool will be extremely helpful once you figure out and are able to finish a good system for pulling or setting gear. Thank you again!
